In [8]:
import numpy as np

In [19]:
# 1 Tensor

A = [[[23,50,7,12],[75,21,57,12],[57,67,99,43],[87,26,18,84]]]

x = np.array(A)
x

array([[[23, 50,  7, 12],
        [75, 21, 57, 12],
        [57, 67, 99, 43],
        [87, 26, 18, 84]]])

In [22]:
A = [[23,50,19],[7,12,109],[57,67,98]]
B = [17,22,19]

aa = np.array(A)
bb = np.array(B)

print(aa*bb)

[[ 391 1100  361]
 [ 119  264 2071]
 [ 969 1474 1862]]


In [37]:
C = [[23,50,19], [7,12,109], [57,67,98]]

cc = np.transpose(C)
print(cc)

cd = np.array(C)
np.linalg.det(C)


[[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]


131344.0000000002

In [38]:
print("")
ci = np.array(C)
np.linalg.inv(C)

array([[-0.0466485 , -0.02761451,  0.03975819],
       [ 0.04208034,  0.00891552, -0.01807467],
       [-0.00163692,  0.0099662 , -0.00056341]])