In [50]:
import numpy as np

In [51]:
A = [[1, -1], [6, 4]]
B = [1],[3]


In [52]:
x = np.array(A)
print(x)

np.linalg.eig(x)

[[ 1 -1]
 [ 6  4]]


(array([2.5+1.93649167j, 2.5-1.93649167j]),
 array([[-0.23145502+0.29880715j, -0.23145502-0.29880715j],
        [ 0.9258201 +0.j        ,  0.9258201 -0.j        ]]))

In [53]:
eigValA,eigVecA = np.linalg.eig(A)
print(eigValA)
print(eigVecA)

[2.5+1.93649167j 2.5-1.93649167j]
[[-0.23145502+0.29880715j -0.23145502-0.29880715j]
 [ 0.9258201 +0.j          0.9258201 -0.j        ]]


Eigen value = [2.5+1.93649167j 2.5-1.93649167j]