In [1]:
import numpy as np
import sympy as sy
from sympy import *
x = Symbol('x')

In [5]:
def f(x,y):
    return 3*x + 4*y - 5

x = np.linspace(1,10)
y = np.linspace(1,10)

z = np.array([[f(i,j) for i in x] for j in y])
dx,dy = np.gradient(z)
print (dx, dy)


[[0.73469388 0.73469388 0.73469388 ... 0.73469388 0.73469388 0.73469388]
 [0.73469388 0.73469388 0.73469388 ... 0.73469388 0.73469388 0.73469388]
 [0.73469388 0.73469388 0.73469388 ... 0.73469388 0.73469388 0.73469388]
 ...
 [0.73469388 0.73469388 0.73469388 ... 0.73469388 0.73469388 0.73469388]
 [0.73469388 0.73469388 0.73469388 ... 0.73469388 0.73469388 0.73469388]
 [0.73469388 0.73469388 0.73469388 ... 0.73469388 0.73469388 0.73469388]] [[0.55102041 0.55102041 0.55102041 ... 0.55102041 0.55102041 0.55102041]
 [0.55102041 0.55102041 0.55102041 ... 0.55102041 0.55102041 0.55102041]
 [0.55102041 0.55102041 0.55102041 ... 0.55102041 0.55102041 0.55102041]
 ...
 [0.55102041 0.55102041 0.55102041 ... 0.55102041 0.55102041 0.55102041]
 [0.55102041 0.55102041 0.55102041 ... 0.55102041 0.55102041 0.55102041]
 [0.55102041 0.55102041 0.55102041 ... 0.55102041 0.55102041 0.55102041]]
